#!/usr/bin/env bash
TOPLEVEL=$(git rev-parse --show-toplevel)
RCFILE=$TOPLEVEL/docs/pylint.rc

IGNORED_FILES="
hotdoc/extensions/gi/gi_extension.py
hotdoc/extensions/c/utils.py
hotdoc/extensions/gi/transition_scripts/hotdoc_gtk_doc_porter
"

IGNORE_ARGS=""
for f in $IGNORED_FILES; do
    IGNORE_ARGS="$IGNORE_ARGS --ignore=$f"
done
echo "Pylint ignoring files:$IGNORED_FILES" | tr "\n" " "
echo

git-pylint-commit-hook --suppress-report --pylint-params="--disable=locally-disabled --disable=fixme --disable=import-error --disable=missing-docstring --unsafe-load-any-extension=y" $IGNORE_ARGS --limit=10.0
git_pep8_commit_hook --pep8-params="--repeat --ignore=E501,E128"
