#!/usr/bin/python
# -*- Mode: Python -*-
# Copyright (C) 2015 Mathieu Duponchelle
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#

import sys, os, traceback
import cPickle as pickle

from hotdoc.core.doc_tool import DocTool

if __name__=="__main__":
    doc_tool = DocTool()

    try:
        doc_tool.setup(sys.argv[1:])
        doc_tool.format()
        doc_tool.persist()
        doc_tool.finalize()
    except Exception as e:
        if os.environ.get ("DOC_DEBUG"):
            traceback.print_exc ()
        else:
            print e.message
        sys.exit (1)
    sys.exit(0)
